### ISSUE TITLE
List all ubuntu snaps

### ISSUE THREAD

**Issue by arshubham** [bartzaalberg/snaptastic#17]
Is it within the scope of this project or app center will show the snaps in itself in the future? It will be an easier way for new users to get slack, vscode etc.

**Comment by unbelievableflavour** [comment]
It is not within the scope of this app. 

The app would act like an appcenter/store. And this is prohibited by appcenter. I will make it easy to click install on the snapcraft.io/store pages and open the snap in the application. So that could serve as your store and make it easier for you. But this is still wip.

Closing this.
