### ISSUE TITLE
Fails to handle snap URLS

### ISSUE THREAD

**Issue by Rosselman** [bartzaalberg/snaptastic#69]
When I try to open a Snap link from my browser (Chrome), for example a Snapcraft install, I get a snap store prompt instead of Snaptastic. I already tried to run `sudo update-desktop-database /usr/share/applications` and it didn't fix the problem.
![screenshot from 2019-03-03 06-20-01](https://user-images.githubusercontent.com/28425525/53693265-cdd46a80-3d7c-11e9-8879-48d65738b551.png)

**Comment by unbelievableflavour** [comment]
Did you install Snaptastic from App Center? You shouldn't have to run that command if installed through App Center.

**Comment by Rosselman** [comment]
Yes, it's installed from the App Center. I only tried the command because I was getting that prompt already.

**Comment by unbelievableflavour** [comment]
Are you maybe on an older version of elementary os? Because for me it works fine :/

**Comment by w0xel** [comment]
Had the same issue, solved by going to the Firefox settings:

![firefox_snaptastic](https://user-images.githubusercontent.com/12088060/56161628-478d8400-5fca-11e9-86a0-8c6041fd01f7.png)

The setting was at `Use Handler for snap:// URIs (default)`. Manually setting to `Use Snaptastic` did the trick, which resulted in the same prompt as OP had. I guess this happens when you already tried to open the snap-store link and just pressed OK when prompted for the default action to happen. (Because Firefoxs default is `Always Ask`). 

I guess you can close this, but please add a note to the README.md

**Comment by unbelievableflavour** [comment]
Added a note to README.md. Closing this.
